// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEsj-bCQ8XgOM6UVSv4OkVWrNvIGtNw0',
    appId: '1:64165290233:web:eecfe95297fed13a76c228',
    messagingSenderId: '64165290233',
    projectId: 'fir-app-f22a9',
    authDomain: 'fir-app-f22a9.firebaseapp.com',
    storageBucket: 'fir-app-f22a9.firebasestorage.app',
    measurementId: 'G-H856YN47N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIyaCZpKeHm9kZyX28_kWTJYshUaMouNg',
    appId: '1:64165290233:android:ee61386d5f69689676c228',
    messagingSenderId: '64165290233',
    projectId: 'fir-app-f22a9',
    storageBucket: 'fir-app-f22a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwedmEkkdnfobb6iVhKAvV2syHkmLCLtU',
    appId: '1:64165290233:ios:a500e10cb3a5a23676c228',
    messagingSenderId: '64165290233',
    projectId: 'fir-app-f22a9',
    storageBucket: 'fir-app-f22a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterDers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwedmEkkdnfobb6iVhKAvV2syHkmLCLtU',
    appId: '1:64165290233:ios:a500e10cb3a5a23676c228',
    messagingSenderId: '64165290233',
    projectId: 'fir-app-f22a9',
    storageBucket: 'fir-app-f22a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterDers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEsj-bCQ8XgOM6UVSv4OkVWrNvIGtNw0',
    appId: '1:64165290233:web:f076e1797f7fdd1f76c228',
    messagingSenderId: '64165290233',
    projectId: 'fir-app-f22a9',
    authDomain: 'fir-app-f22a9.firebaseapp.com',
    storageBucket: 'fir-app-f22a9.firebasestorage.app',
    measurementId: 'G-X87G3F0RS4',
  );
}
